### ISSUE TITLE
bug in changing the time and date in countdown clock

### ISSUE THREAD

**Issue by Rafaelbarlev** [WPDevelopers/essential-addons-for-elementor-lite#484]
Hello EA Support
Bug when traying to change the date or to change the time in Visible until. 
Attached two screen shots.
Thank you 
Rafael

![New Picture (3)](https://user-images.githubusercontent.com/63585247/79151113-9256fd00-7dd2-11ea-88a3-e25132767a6c.jpg)
![New Picture (4)](https://user-images.githubusercontent.com/63585247/79151116-93882a00-7dd2-11ea-914d-578457d01aa1.jpg)

**Comment by khan-rafin-ahmed** [comment]
@Rafaelbarlev,

It was a conflict with another plugin. Your issue should have been resolved by now if all your plugins are up-to-date.

Thank you!

**Comment by Rafaelbarlev** [comment]
Hello

I have just checked my page and I’m sorry to inform you that the same issue
with the plugin still persists.

Thank you

**Comment by Rafaelbarlev** [comment]
Hello
I have just checked my page and I’m sorry to inform you that the same issue with the plugin still persists.
Thank you

**Comment by sabuz** [comment]
Did you clear cache/force reload the page?

**Comment by robinwpdeveloper** [comment]
Closing this ticket due to lack of activity. 
Feel free to reopen if the issue still exists.

Details needed for debugging:
- Screencast of the issue
- Essential Addons for Elementor version/s
- Elementor version/s
- PHP version 
- Is it multisite?
- WordPress version (Optional but good to have)
