### ISSUE TITLE
Post Grid Error Headings

### ISSUE THREAD

**Issue by MarLMazo** [WPDevelopers/essential-addons-for-elementor-lite#564]
On the Post Grid Widget, Changing the Heading Title Tag won't affect the current Tag and still use the Default H2 Heading even you select h3 or so. Also in the same issue, customizing the style of the Heading such as changing the font-size won't affect the Title. 

![image](https://user-images.githubusercontent.com/42755897/97754071-3f723800-1acd-11eb-8c73-7bf8961579b3.png)
All the default style is doing the same thing.

As I investigate further, I was able to fix it, it turns out that the H2 Heading is hardcoded on the template and the heading has an anchor child element, thus it won't change the design of the heading because the title is embedded on the anchor element.

![image](https://user-images.githubusercontent.com/42755897/97754087-47ca7300-1acd-11eb-98ef-8caf8aa28ab2.png)

So, I just make the heading dynamic and write the heading element inside the anchor element so the styling should work. 
I hope this helps and be able to fix it on the next update.

**Comment by abid112** [comment]
Hi @MarLMazo ,

Yes, We already aware about this issue. This will be fixed in the future release of Essential Addons for Elementor.
And thank you so much for sharing your fix here. I really appreciate it. This will help us to quickly fix this issue from our end.

Thanks!

**Comment by abid112** [comment]
Hi @MarLMazo ,

Hope you're doing good. Today we released a new version of Essential Addons for Elementor(4.3.4) where we fixed the issue where the Title Tag doesn't reflect the Post Grid title.
So can you please update your plugin to 4.3.4 and check now.

Let me know how it goes.
Thanks!

**Comment by MarLMazo** [comment]
Hi,
I update the Plugin and the changing headings work now properly

But changing the Font-size of the Heading is still not working properly. 
It's still having a markup of <h2><a href="#">TITLE</a></h2>

That's why changing the heading font-size looks like adding padding on the anchor tag. 
In my opinion, it should be like this: <a href="#"><h2>TITLE</h2></a>
