### ISSUE TITLE
Pricing table

### ISSUE THREAD

**Issue by Casw777** [WPDevelopers/essential-addons-for-elementor-lite#646]
Hello

After latest update presing "button" in "pricing table" opens page in new tab. Before update page opened in the same tab.  Under "link option" option "open in new windows" is unchecked. How can i resolved this? Thanks.

**Comment by abid112** [comment]
Hi @Casw777 ,

We are already aware of this issue and it has been fixed in one of the dev branch.  This will be live in the future release don't worry.

Sorry for the inconvenience.

**Comment by abid112** [comment]
Hi @Casw777 ,

We released a new update today where we fixed this issue.
So please update your Essential Addons for Elementor(v4.6.6) to resolve this issue.

Thank you!

**Comment by Casw777** [comment]
hi
Unfortunatelly this update didnt fix the issue. I purged cashe, checked the option "open in new window'. Maybe i did something wrong?

**Comment by Casw777** [comment]
Hi

Now everything works. Thank you!

**Comment by abid112** [comment]
You're welcome @Casw777 !
