### ISSUE TITLE
version >=4.6.1 is causing problems with the Image Accordion widget overlay color

### ISSUE THREAD

**Issue by Azertooth** [WPDevelopers/essential-addons-for-elementor-lite#647]
from the 4.6.1 and newer versions upgrade I can't change the overlay colors (including the hover one) of the image accordion widget. I can select the color i want from the widget settings but it won't apply, the image continue to display the default color values. All was working well with 4.6.0

I tried to temporanearly switch back to 4.6.0 and it solved this problem (confirming that some change in the 4.6.1 changelog broke it) but now your base plugin don't recognize the essentials addons Pro so the Pro widgets I was using are broken. If I try to deactivate/activate or uninstall/reinstall the essentials addons Pro plugin it is recognized but doing this your base plugin upgrade automatically to latest version (4.6.3) bringing me back to the intial bug. I'm stuck

**Comment by abid112** [comment]
Hi @Azertooth ,

Sorry for the inconvenience.
We’re already aware of this issue and this has been fixed in one of our dev branch. This will be live in the future release don't worry.
For this time being, you can use this dev version: https://d.pr/f/lbApB1 

Thanks for your patience!

**Comment by Azertooth** [comment]
I tried the dev version you linked me but the accordion overlay colors are still broken (assets regenerated after install), switched back to 4.6.0 for now

**Comment by abid112** [comment]
Hi @Azertooth , Can you please try this one: https://d.pr/f/hwqiWQ
After install please regenerate your assets from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://d.pr/i/23N5eb

However, we're preparing a new update next week with this fix.
Thank you!

**Comment by abid112** [comment]
Hi @Azertooth ,

We released a new update today where we fixed this issue.
So please update your Essential Addons for Elementor(v4.6.6) to resolve this issue.

Thank you!

**Comment by Azertooth** [comment]
> Hi @Azertooth ,
> 
> We released a new update today where we fixed this issue.
> So please update your Essential Addons for Elementor(v4.6.6) to resolve this issue.
> 
> Thank you!

can confirm that the issue is solved, thank you Abid
