### ISSUE TITLE
anchor link support for nested ea advanced tabs

### ISSUE THREAD

**Issue by Azertooth** [WPDevelopers/essential-addons-for-elementor-lite#711]
Referring to #686:
with the latest update you introduced `EA Advanced Tabs & Advanced Accordion | Custom ID Anchor not working with links on same page` but for nested tabs is still kinda broken: the links works and it select the right nested tabs (highlighting the title) but the content of the tabs do not match, it reports the content of the first nested tabs from left

**Comment by sadmansakibnadvi** [comment]
Hello there,

Greetings.

Sorry for the inconvenience and thanks for pointing this out. We have found the issue on Advanced tabs as well but didn't find any issue with the advanced accordion. I have already informed our dev team about it and they are working on the advanced tabs. Can you please create a support ticket for advanced accordion with temporary login access from here so that we can check from your end: https://wpdeveloper.com/support/new-ticket 

I will update you as soon as the issue is fixed. Thank you and have a great day.

**Comment by Azertooth** [comment]
Hi @sadmansakibnadvi and thank you for joining the discussion

I confirm that the problem is affecting advanced tabs in a nested configuration (advanced tabs as template for advanced tabs) and that I do not use advanced accordion

**Comment by sadmansakibnadvi** [comment]
Hello @Azertooth,

Greetings.

Thanks for clearing it out. Our dev team is working on it. Please allow us some time.

Have a great day.

**Comment by sadmansakibnadvi** [comment]
Hello there,

We have fixed this issue on a Dev Version. Please download and install this version from this link - https://d.pr/f/V9eoaO

Hopefully, it will help you to fix your issue. ​​Let me know how it goes.

Thank you.

**Comment by abid112** [comment]
Hi @Azertooth 

We've fixed this issue in the latest version of Essential Addons for Elementor **v5.0.2**
Feel free to update the plugin to get this resolved!

Thanks!

**Comment by Azertooth** [comment]
Unfortunately the update 5.0.2 didn't fix the problem and clicking on the anchor link now won't even select the anchored tab; I'll try to explain the case better:
I have nested tabs, so on my page I have the EA Advanced Tabs addon with 4 tabs. Each one of this 4 tabs has a separate content type template settings; this 4 templates consist in a blank canva in which is present a EA Advanced Tabs addon with 4 tabs, So it's like:
```

                                                            PAGE

         TAB1                               TAB2                          TAB3                                TAB4
           |                                 |                              |                                  |
           |                                 |                              |                                  |
           |                                 |                              |                                  |
TAB11   TAB12   TAB13   TAB14       TAB21   TAB22   TAB23   TAB24       TAB31   TAB32   TAB33   TAB34        TAB41   TAB42   TAB43   TAB44
```

Eg. If I anchor link TAB14 inside TAB11 and click on the link, it reload the page but remain on TAB11 instead of selecting TAB14

**Comment by sadmansakibnadvi** [comment]
Hello there,

Greetings.

Can you please share the link to your page where you are having the issue?

We will check and get back to you as soon as possible.

Thank you.

**Comment by Azertooth** [comment]
> Hello there,
> 
> Greetings.
> 
> Can you please share the link to your page where you are having the issue?
> 
> We will check and get back to you as soon as possible.
> 
> Thank you.

Unfortunately I can not. Are you able to create this exact structure and replicate the problem?

**Comment by sadmansakibnadvi** [comment]
Hello @Azertooth,

Greetings.

This issue has been resolved. Did you update the plugin? Do you still have this issue?

Let me know. Thank you.

**Comment by Azertooth** [comment]
> Hello @Azertooth ,
> 
> Greetings. Thanks for explaining the issue so well.
> 
> I recreated the same issue and it is still there. I have already informed our dev team about the issue. They are working on it. We are doing some tests. I will share the dev version as soon as it is ready.
> 
> Thank you so much for your time.

@sadmansakibnadvi I was waiting for an update on this second scenario that's related to the original issue but was never updated about

**Comment by Azertooth** [comment]
Thank you for the response @sadmansakibnadvi 

I updated the plugin to the latest version and can confirm that all is working as expected now! Thank you so much for your commitment to this rare scenario bug

**Comment by sadmansakibnadvi** [comment]
Hello @Azertooth, 

Thank you so much for your kind words. It means a lot to us. If you don't mind me asking, could you do me a favor, and spend 30-sec to review us following this link, this will help us to serve better. Thank you in advance! Link to review - [http://wpdeveloper.com/review-essential-addons-elementor](http://wpdeveloper.net/review-essential-addons-elementor)

Have a great day.

**Comment by Azertooth** [comment]
Hi @sadmansakibnadvi 

It won't work properly anymore on latest plugin version:

Elementor: 3.5.6
EA: 5.0.10
EA Pro: 5.0.8
